#pragma config(Sensor, S1,     leftT,          sensorEV3_Touch)
#pragma config(Sensor, S4,     rightT,         sensorEV3_Touch)
#pragma config(Motor,  motorB,          leftW,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightW,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void reverse();
void moveForward();
task handleTouch();
task moveBot();
task turnLeft();
task turnRight();
void getNewRatio();
int reversing = 0;
int stopMoving = 0;
//the ratio will changing overtime
int myRatio = 5;
int myExpectedSpeedLeft, myExpectedSpeedRight;
int myRatioArray[11] = {
	-35,
	-30,
	-20,
	-15,
	-10,
	0,
	10,
	15,
	20,
	30,
	35
};


task main()
{
	displayCenteredBigTextLine(3, "in main");
	//getNewRatio();

	startTask(moveBot);
	wait1Msec(500);
	startTask(handleTouch);
	while(true){};
	//resetMotorEncoder(leftW);
	//resetMotorEncoder(rightW);

	//setMotorTarget(leftW, 1000, 50);
	//repeatUntil(getMotorEncoder(leftW) == getMotor
	/*
	while(true){
		int rpm = getMotorRPM(leftW);
		if(rpm < 100) {

			displayCenteredBigTextLine(3, "%d rpm", rpm);
			sleep(2);
		}
		setMotorSync(leftW,rightW,0,50);
	}*/
/*	int speed,speed2, leftRPM, rightRPM;
	while(true) {
			setMotorSync(leftW,rightW,0,50);
			speed = getMotorSpeed(leftW);
			speed2 = getMotorSpeed(rightW);
			displayCenteredBigTextLine(2, "left %d", speed);
			displayCenteredBigTextLine(4, "right %d", speed2);
		leftRPM = getMotorRPM(leftW);
		rightRPM = getMotorRPM(rightW);
		displayCenteredBigTextLine(8, "%d, %d", leftRPM, rightRPM);
			if(speed<20) {
				playTone(600,1);
		}
		wait1Msec(300);}*/

}

task moveBot() {
	stopTask(turnLeft);
	stopTask(turnRight);
	moveForward();
}

void reverse() {
	reversing = 1;
	stopMoving = 1;
	setMotorSync(leftW,rightW,0,-50);
	wait1Msec(random(400)+800);
	setMotorSync(leftW,rightW,0,0);
	wait1Msec(2000);
	playTone(600,1);
	stopMoving = 0;
	int dir = random(1);
	if (dir == 0)
		startTask(turnLeft);
	else
		startTask(turnRight);
}


void moveForward() {
	int leftRPM, rightRPM;
	while (true) {
		leftRPM = getMotorRPM(leftW);
		rightRPM = getMotorRPM(rightW);
		displayCenteredBigTextLine(8, "%d, Act. %d", leftRPM, rightRPM);
		displayCenteredBigTextLine(12, "%d, Exp. %d", myExpectedSpeedLeft,myExpectedSpeedRight);
		myExpectedSpeedLeft = getMotorRPM(leftW);
		myExpectedSpeedRight = getMotorRPM(rightW);
		getNewRatio();
		wait1Msec(1000);
	}
}

void getNewRatio() {
			int i, j, k;
			int arr[10];
			for (i = 0; i < 10;) {
				for (j = 0; j < myRatio; j++) {
					arr[i++] = myRatio - 1;
				}
				for (k = myRatio; k < 10; k++) {
					arr[i++] = myRatio + 1;
				}
		  }
		  int randomInt = random(9);
		  int selection = arr[randomInt];
		  if (selection == 0 || selection == 10) {
		  	myRatio = 5;
		  } else
		  myRatio = selection;
			setMotorSync(leftW,rightW,myRatioArray[selection],50);
}

task handleTouch() {
	displayCenteredBigTextLine(6, "in sensor");
	int leftRPM, rightRPM;
	int leftPushing = 0;
	int rightPushing = 0;
	while (true) {
		leftRPM = getMotorRPM(leftW);
		rightRPM = getMotorRPM(rightW);
		displayCenteredBigTextLine(8, "%d, %d", leftRPM, rightRPM);
		if ( leftRPM< myExpectedSpeedLeft - 10 ||  rightRPM< myExpectedSpeedRight - 10) {

			myExpectedSpeedLeft = getMotorRPM(leftW);
			myExpectedSpeedRight = getMotorRPM(rightW);
			wait1Msec(20);
			stopTask(moveBot);
			//setMotorSync(leftW,rightW,0,0);
			if (leftRPM < myExpectedSpeedLeft - 10 && stopMoving == 0 ) {
				leftPushing = 1;
			}
			if (rightRPM< myExpectedSpeedRight - 10 && stopMoving == 0) {
				rightPushing = 1;
			}
		}
		if(leftPushing && rightPushing && stopMoving == 0) {
			leftPushing = 0;
			rightPushing = 0;
			playSound(soundBeepBeep);
			reverse();
			wait1Msec(700);
		}
		else if (leftPushing) {
			leftPushing = 0;
			rightPushing = 0;
			startTask(turnRight);
			wait1Msec(700);
		}
		else if (rightPushing) {
			leftPushing = 0;
			rightPushing = 0;
			startTask(turnLeft);
			wait1Msec(700);
		}
	}
}


task turnLeft() {
	while (true) {
		if (reversing == 0) {
			displayCenteredBigTextLine(10, "reverse");
			setMotorSync(leftW,rightW,0,-50);
			wait1Msec(random(400)+800);
		}
		reversing = 0;
		setMotorSync(leftW,rightW,-(random(20)+20),50);
		wait1Msec(1000);
		startTask(moveBot);
	}
}


task turnRight() {
	while (true) {
		if (reversing == 0) {
			setMotorSync(leftW,rightW,0,-50);
			wait1Msec(random(400)+800);
		}
		reversing = 0;
		setMotorSync(leftW,rightW,(random(20)+20),50);
		wait1Msec(1000);
		startTask(moveBot);
	}
}
