#pragma config(Sensor, S1,     leftT,          sensorEV3_Touch)
#pragma config(Sensor, S4,     rightT,         sensorEV3_Touch)
#pragma config(Motor,  motorB,          leftW,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightW,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void reverse();
void moveForward();
void handleTouch();
void turnLeft();
void turnRight();
void getNewRatio();
int leftPushed = 0;
int rightPushed = 0;
int myRatio = 0;


task main()
{
	moveForward();
}

void reverse() {
	setMotorSync(leftW,rightW,0,-50);
	wait1Msec(500);
	playTone(600,1);
	turnLeft();
	moveForward();
}


void moveForward() {
	  leftPushed = 0;
	  rightPushed = 0;
		repeatUntil(getTouchValue(leftT)==1 || getTouchValue(rightT)==1) {
			setMotorSync(leftW,rightW,0,50);
			//getNewRatio();
			//wait1Msec(1000);
		}
		wait1Msec(100);
		setMotorSync(leftW,rightW,0,0);
		wait1Msec(100);
		if (getTouchValue(leftT)==1) {
			leftPushed = 1;
			setMotorSync(leftW,rightW,0,0);
		}
		wait1Msec(50);
		if (getTouchValue(rightT)==1) {
			rightPushed = 1;
			setMotorSync(leftW,rightW,0,0);
		}
		wait1Msec(50);
		handleTouch();
}

void getNewRatio() {
			setMotorSync(leftW,rightW,myRatio,0);
}

void handleTouch() {
		if(leftPushed && rightPushed) {
			playSound(soundBeepBeep);
			reverse();
		}
		else if (leftPushed) {
			playSound(soundException);
			turnRight();
		}
		else if (rightPushed) {
			playSound(soundBlip);
			turnLeft();
		}
	  wait1Msec(100);
}


void turnLeft() {
	setMotorSync(leftW,rightW,0,-50);
	wait1Msec(500);
	repeatUntil(getTouchValue(leftT)==1 || getTouchValue(rightT)==1) {
		  setMotorSync(leftW,rightW,0,-50);
		  wait1Msec(500);
			setMotorSync(leftW,rightW,-25,50);
			wait1Msec(1000);
			moveForward();
		}
		wait1Msec(100);
		setMotorSync(leftW,rightW,0,0);
		wait1Msec(100);
		if (getTouchValue(leftT)==1) {
			leftPushed = 1;
			setMotorSync(leftW,rightW,0,0);
		}
		wait1Msec(50);
		if (getTouchValue(rightT)==1) {
			rightPushed = 1;
			setMotorSync(leftW,rightW,0,0);
		}
		wait1Msec(50);
		handleTouch();
}


void turnRight() {
	setMotorSync(leftW,rightW,0,-50);
	wait1Msec(500);
	repeatUntil(getTouchValue(leftT)==1 || getTouchValue(rightT)==1) {
			setMotorSync(leftW,rightW,25,50);
			wait1Msec(1000);
			moveForward();
		}
		wait1Msec(100);
		setMotorSync(leftW,rightW,0,0);
		wait1Msec(100);
		if (getTouchValue(leftT)==1) {
			leftPushed = 1;
			setMotorSync(leftW,rightW,0,0);
		}
		wait1Msec(50);
		if (getTouchValue(rightT)==1) {
			rightPushed = 1;
			setMotorSync(leftW,rightW,0,0);
		}
		wait1Msec(50);
		handleTouch();


}
