#pragma config(Sensor, S1,     leftT,          sensorEV3_Touch)
#pragma config(Sensor, S4,     rightT,         sensorEV3_Touch)
#pragma config(Motor,  motorB,          leftW,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightW,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void reverse();
void moveForward();
task handleTouch();
task moveBot();
task turnLeft();
task turnRight();
void getNewRatio();
int reversing = 0;
int myRatio = 5;
int myRatioArray[11] = {
				-50,
				-40,
				-30,
				-20,
				-10,
				0,
				10,
				20,
				30,
				40,
				50
									 };

task main()
{
	displayCenteredBigTextLine(3, "in main");

	startTask(handleTouch);
	startTask(moveBot);
	//moveForward();
	while (true);
}

task moveBot() {
	stopTask(turnLeft);
	stopTask(turnRight);
	displayCenteredBigTextLine(2, "in moveBot");
	moveForward();
}

void reverse() {
	reversing = 1;
	setMotorSync(leftW,rightW,0,-50);
	wait1Msec(random(400)+800);
	setMotorSync(leftW,rightW,0,0);
	wait1Msec(2000);
	playTone(600,1);
	int dir = random(1);
	if (dir == 0)
		startTask(turnLeft);
	else
		startTask(turnRight);
}


void moveForward() {
	  while (true) {
			getNewRatio();
			wait1Msec(300);
		}
}

void getNewRatio() {
			int i, j, k;
			int arr[10];
			for (i = 0; i < 10;) {
				for (j = 0; j < myRatio; j++) {
					arr[i++] = myRatio - 1;
				}
				for (k = myRatio; k < 10; k++) {
					arr[i++] = myRatio + 1;
				}
		  }
		  int randomInt = random(9);
		  int selection = arr[randomInt];
			setMotorSync(leftW,rightW,myRatioArray[selection],50);
}

task handleTouch() {
	displayCenteredBigTextLine(6, "in sensor");
	int leftPushing = 0;
	int rightPushing = 0;
	while (true) {
		if (getTouchValue(leftT)==1 || getTouchValue(rightT)==1) {
			displayCenteredBigTextLine(8, "can you see me");
			wait1Msec(20);
			stopTask(moveBot);
			setMotorSync(leftW,rightW,0,0);
			if (getTouchValue(leftT) == 1) {
				leftPushing = 1;
			}
			if (getTouchValue(rightT) == 1) {
				rightPushing = 1;
			}
		}
			if(leftPushing && rightPushing) {
				leftPushing = 0;
				rightPushing = 0;
				playSound(soundBeepBeep);
				reverse();
				wait1Msec(700);
			}
			else if (leftPushing) {
				leftPushing = 0;
				rightPushing = 0;
				startTask(turnRight);
				wait1Msec(700);
			}
			else if (rightPushing) {
				leftPushing = 0;
				rightPushing = 0;
				startTask(turnLeft);
				wait1Msec(700);
			}
		}
}


task turnLeft() {
	while (true) {
		if (reversing == 0) {
			displayCenteredBigTextLine(10, "reverse");
			setMotorSync(leftW,rightW,0,-50);
			wait1Msec(random(400)+800);
		}
		reversing = 0;
		setMotorSync(leftW,rightW,-(random(20)+20),50);
		wait1Msec(1000);
		startTask(moveBot);
	}
}


task turnRight() {
	while (true) {
		if (reversing == 0) {
			setMotorSync(leftW,rightW,0,-50);
			wait1Msec(random(400)+800);
		}
		reversing = 0;
		setMotorSync(leftW,rightW,(random(20)+20),50);
		wait1Msec(1000);
		startTask(moveBot);
	}
}
